### ISSUE TITLE
A problem about data

### ISSUE THREAD

**Issue by xsf777** [zouzhenhong98/SensatUrban-BEV-Seg3D#2]
![image](https://user-images.githubusercontent.com/89497789/195891640-db86f34f-283e-4ef6-a9a6-ffaee092da60.png)
SensatUrban数据集分为train,val,test，train和val数据都是N×7，test是N程6（没有class），但是在point_EDA_31.py内生成test的BEV时并没有按照N×6的形式进行处理而是N×7.

**Comment by xiaohe3625** [comment]
> ![image](https://user-images.githubusercontent.com/89497789/195891640-db86f34f-283e-4ef6-a9a6-ffaee092da60.png) SensatUrban数据集分为train,val,test，train和val数据都是N×7，test是N程6（没有class），但是在point_EDA_31.py内生成test的BEV时并没有按照N×6的形式进行处理而是N×7.

你好，我也碰到这个问题，请问这个问题你解决吗？

**Comment by BKINGING** [comment]
> ![image](https://user-images.githubusercontent.com/89497789/195891640-db86f34f-283e-4ef6-a9a6-ffaee092da60.png) SensatUrban数据集分为train,val,test，train和val数据都是N×7，test是N程6（没有class），但是在point_EDA_31.py内生成test的BEV时并没有按照N×6的形式进行处理而是N×7.

你好，我也碰到这个问题，请问这个问题你解决吗？

**Comment by BKINGING** [comment]
> 

你好，我也碰到这个问题，请问这个问题你解决吗？

**Comment by zouzhenhong98** [comment]
@xsf777 @xiaohe3625 @BKINGING 对于官方test数据，显然我们没有label，因此是不可用的，因此没无法加载class属性。我用的test其实就是validate数据，而在推理的时候，有点忘记推理数据是怎么生产的了，应该和训练数据差不多
