### ISSUE TITLE
请问训练和推理时候用的到底是哪些文件？

### ISSUE THREAD

**Issue by LinLin1031** [zouzhenhong98/SensatUrban-BEV-Seg3D#4]
https://github.com/zouzhenhong98/SensatUrban-BEV-Seg3D/blob/4ce97a05699daa57ddea797923008fe14d9b03dc/preprocess/point_EDA_31.py#L335

还是

https://github.com/zouzhenhong98/SensatUrban-BEV-Seg3D/blob/4ce97a05699daa57ddea797923008fe14d9b03dc/preprocess/point_EDA_31.py#L399

**Comment by BKINGING** [comment]
> https://github.com/zouzhenhong98/SensatUrban-BEV-Seg3D/blob/4ce97a05699daa57ddea797923008fe14d9b03dc/preprocess/point_EDA_31.py#L335
> 
> 还是
> 
> https://github.com/zouzhenhong98/SensatUrban-BEV-Seg3D/blob/4ce97a05699daa57ddea797923008fe14d9b03dc/preprocess/point_EDA_31.py#L399

Excuse me, I met this situation what should I do? python /media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py
0it [00:00, ?it/s]loading 6 files

loading file /media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/dataloaders/datasets/data_release/test/birmingham_block_2.ply[00:00<?, ?it/s]
0%| | 0/6 [00:00<?, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 641, in
Sensat.evaluate_batch(Sensat.evaluate_batch_nn(Sensat.eval_offline_img2pts))
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 624, in evaluate_batch
miou, iou_list, gt_list, oacc, macc = batch_mIoU(batch_iterator)
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/helper_metrics.py", line 83, in batch_mIoU
for preds, gt in tqdm(iter_data):
File "/home/hubu/anaconda3/envs/Segment/lib/python3.7/site-packages/tqdm/std.py", line 1182, in iter
for obj in iterable:
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 606, in evaluate_batch_nn
ply_data = self.load_points(ply_path, reformat=True)
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 155, in load_points
c = _ply_data["class"]
ValueError: no field of name class

**Comment by QiLi0226** [comment]
同问，我preprocess后得到了alt,rgb,cls,vis，但是训练的好像是rgbd四通道数据？有点没明白

**Comment by Lrainhom** [comment]
> 同问，我preprocess后得到了alt,rgb,cls,vis，但是训练的好像是rgbd四通道数据？有点没明白

i meet the same problem

**Comment by LinLin1031** [comment]
> > 同问，我preprocess后得到了alt,rgb,cls,vis，但是训练的好像是rgbd四通道数据？有点没明白
> 
> i meet the same problem

The code provided is faulty and my advice is to stop trying to reproduce it. Ahhh..

**Comment by zouzhenhong98** [comment]
@LinLin1031 @QiLi0226 @crossover10 sorry for late response. alt是高程（altitude），rgb是航拍图，cls是分类结果着色为灰度图，vis是cls着色为RGB，训练数据是rgb+alt，拼接alt和rgb的代码我可能没有加入repo，不过也很简单。所以改进方式是，要么你们把输入从4通道改成3通道适配单独的rgb文件输入，要么自己尝试一下拼接rgb和alt，并保存为png格式，JPG不支持4通道图像。

**Comment by zouzhenhong98** [comment]
@BKINGING 我想整个数据处理的过程是简单的，如果code有些bug可以尝试修复，或者在各自的代码中重新实现，如果对于数据处理或者模型推理的过程有不清楚的欢迎和我邮件沟通，github登陆比较少。I believe the entire data processing workflow should be simple. If there are any bugs present in the code, they can certainly be attempted to fix, or the affected parts can be re-implemented within each respective codebase. Should there be any unclear aspects about the data processing steps or the model inference process, please feel free to reach out to me via email for clarification. Note that I am less active on GitHub.
