### ISSUE TITLE
Confusion about the training data

### ISSUE THREAD

**Issue by QiLi0226** [zouzhenhong98/SensatUrban-BEV-Seg3D#6]
您好！我preprocess后得到了alt,rgb,cls,vis，但是训练的好像是rgbd四通道数据？有点没明白能麻烦解答一下嘛

**Comment by zouzhenhong98** [comment]
alt是高程（altitude），rgb是航拍图，cls是分类结果着色为灰度图，vis是cls着色为RGB，训练数据是rgb+alt
